VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FaultPoint"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database

'Public Function AddPoint(id As Long, fType As String, Lat As Double, Lon As Double, Alt As Double, _
    gpstime As Date, radius As Integer, color As String, opacity As Integer, fill As Boolean, fillcolor As String, fillopacity As Integer, weight As Integer) As Boolean
    
    Public id As Long
    Public fType As String
    Public Lat As Double
    Public Lon As Double
    Public Alt As Double
    Public gpstime As Date
    Public radius As Integer
    Public color As String
    Public opacity As Integer
    Public fill As Boolean
    Public fillcolor As String
    Public fillopacity As Integer
    Public weight As Integer
    
    

